<?php
/**
 * Localizations for the Kolab 2-Factor-Auth plugin
 *
 * Copyright (C) 2015, Kolab Systems AG
 *
 * For translation see https://www.transifex.com/projects/p/kolab/resource/kolab_2fa/
 */
$labels['created'] = 'Vytvořeno';
$labels['remove'] = 'Odstranit';
$labels['continue'] = 'Pokračovat';
$labels['yes'] = 'ano';
$labels['no'] = 'ne';
$labels['label'] = 'Název';
$labels['enterhighsecurity'] = 'Potvrdit';
