<?php
/**
 * Localizations for the Kolab 2-Factor-Auth plugin
 *
 * Copyright (C) 2015, Kolab Systems AG
 *
 * For translation see https://www.transifex.com/projects/p/kolab/resource/kolab_2fa/
 */
$labels['created'] = 'Oprettet';
$labels['remove'] = 'Fjern';
$labels['continue'] = 'Fortsæt';
$labels['yes'] = 'ja';
$labels['no'] = 'nej';
$labels['label'] = 'Navn';
$labels['enterhighsecurity'] = 'Bekræft';
