<?php
/**
 * Localizations for the Kolab 2-Factor-Auth plugin
 *
 * Copyright (C) 2015, Kolab Systems AG
 *
 * For translation see https://www.transifex.com/projects/p/kolab/resource/kolab_2fa/
 */
$labels['created'] = 'Erstellt';
$labels['remove'] = 'Entfernen';
$labels['continue'] = 'Weiter';
$labels['or'] = 'oder';
$labels['yes'] = 'Ja';
$labels['no'] = 'Nein';
$labels['label'] = 'Name';
$labels['enterhighsecurity'] = 'Bestätigen';
