<?php
/**
 * Localizations for the Kolab 2-Factor-Auth plugin
 *
 * Copyright (C) 2015, Kolab Systems AG
 *
 * For translation see https://www.transifex.com/projects/p/kolab/resource/kolab_2fa/
 */
$labels['created'] = 'Creado';
$labels['remove'] = 'Elminiar';
$labels['continue'] = 'Continuar';
$labels['yes'] = 'si';
$labels['no'] = 'no';
$labels['label'] = 'Nombre';
$labels['enterhighsecurity'] = 'Confirmar';
