<?php
/**
 * Localizations for the Kolab 2-Factor-Auth plugin
 *
 * Copyright (C) 2015, Kolab Systems AG
 *
 * For translation see https://www.transifex.com/projects/p/kolab/resource/kolab_2fa/
 */
$labels['factor'] = 'Tekijä';
$labels['secret'] = 'Salainen avain';
$labels['created'] = 'Luotu';
$labels['remove'] = 'Poista';
$labels['continue'] = 'Jatka';
$labels['settingslist'] = 'Monivaiheinen tunnistautuminen';
$labels['settingstitle'] = 'Tunnistautumistekijät';
$labels['totp'] = 'Mobiilisovellus (TOTP)';
$labels['hotp'] = 'Mobiilisovellus (HOTP)';
$labels['yubikey'] = 'Yubikey';
$labels['or'] = 'tai';
$labels['yes'] = 'kyllä';
$labels['no'] = 'ei';
$labels['label'] = 'Nimi';
$labels['qrcode'] = 'QR-koodi';
$labels['showqrcode'] = 'Näytä QR-koodi';
$labels['yubikeyid'] = 'YubiKey-tunnisteesi';
$labels['yubikeyidexplainyubikey'] = 'Paina YubiKeytasi kerran ja kirjoita luotu koodi';
$labels['addfactor'] = 'Lisää tunnistautumistekijä';
$labels['testfactor'] = 'Testaa tätä tekijää';
$labels['verifycode'] = 'Vahvista koodi';
$labels['loginexpired'] = 'Kirjautumispyyntö vanheni! Yritä uudelleen.';
$labels['authremoveconfirm'] = 'Haluatko varmasti poistaa tämän tunnistautumistekijän tililtäsi?';
$labels['verifycodemissing'] = 'Kirjoita vahvistuskoodi laitteeltasi';
$labels['factorsavesuccess'] = 'Tunnistautumistekijä tallennettu onnistuneesti';
$labels['factorremovesuccess'] = 'Tunnistautumistekijä poistettu onnistuneesti';
$labels['enterhighsecurity'] = 'Vahvista';
