<?php
/**
 * Localizations for the Kolab 2-Factor-Auth plugin
 *
 * Copyright (C) 2015, Kolab Systems AG
 *
 * For translation see https://www.transifex.com/projects/p/kolab/resource/kolab_2fa/
 */
$labels['created'] = 'Créé';
$labels['remove'] = 'Supprimer';
$labels['continue'] = 'Continuer';
$labels['or'] = 'ou';
$labels['yes'] = 'oui';
$labels['no'] = 'non';
$labels['label'] = 'Nom';
$labels['enterhighsecurity'] = 'Confirmer';
