<?php
/**
 * Localizations for the Kolab 2-Factor-Auth plugin
 *
 * Copyright (C) 2015, Kolab Systems AG
 *
 * For translation see https://www.transifex.com/projects/p/kolab/resource/kolab_2fa/
 */
$labels['created'] = 'Created';
$labels['remove'] = 'Eltávolítás';
$labels['continue'] = 'Continue';
$labels['yes'] = 'yes';
$labels['no'] = 'no';
$labels['label'] = 'Név';
$labels['enterhighsecurity'] = 'Confirm';
