<?php
/**
 * Localizations for the Kolab 2-Factor-Auth plugin
 *
 * Copyright (C) 2015, Kolab Systems AG
 *
 * For translation see https://www.transifex.com/projects/p/kolab/resource/kolab_2fa/
 */
$labels['factor'] = 'Czynnik';
$labels['secret'] = 'Tajny klucz ';
$labels['created'] = 'Utworzono';
$labels['remove'] = 'Usuń';
$labels['continue'] = 'Kontynuuj';
$labels['settingslist'] = 'Uwierzytelnianie wieloetapowe';
$labels['settingstitle'] = 'Czynniki uwierzytelniania';
$labels['totp'] = 'Aplikacja mobilna (TOTP)';
$labels['hotp'] = 'Aplikacja mobilna (HOTP)';
$labels['yubikey'] = 'Yubikey';
$labels['or'] = 'lub';
$labels['yes'] = 'tak';
$labels['no'] = 'nie';
$labels['label'] = 'Nazwa';
$labels['qrcode'] = 'Kod QR';
$labels['showqrcode'] = 'Pokaż kod QR';
$labels['qrcodeexplaintotp'] = 'Pobierz aplikację uwierzytelniającą na swój telefon. <strong>FreeOTP</strong> i <strong>Google Authenticator</strong> są przetestowane, ale dowolna aplikacja TOTP powinna również działać.<br/><br/>
Uruchom aplikację na swoim telefonie i zarejestruj tą usługę. Gdy aplikacja o to poprosi, zeskanuj kod QR.';
$labels['qrcodeexplainhotp'] = 'Pobierz aplikację uwierzytelniającą na swój telefon. <strong>Google Authenticator</strong> jest znana z poprawnej pracy, ale dowolna aplikacja HOTP powinna również działać.<br/><br/>
Uruchom aplikację na swoim telefonie i zarejestruj tą usługę. Gdy aplikacja o to poprosi, zeskanuj kod QR.';
$labels['yubikeyid'] = 'Twój identyfikator Yubikey';
$labels['yubikeyidexplainyubikey'] = 'Naciśnij swojego Yubikeya i wprowadź wygenerowany kod';
$labels['addfactor'] = 'Dodaj czynnik uwierzytelniający';
$labels['enterhighsecurity'] = 'Potwierdź';
