<?php
/**
 * Localizations for the Kolab 2-Factor-Auth plugin
 *
 * Copyright (C) 2015, Kolab Systems AG
 *
 * For translation see https://www.transifex.com/projects/p/kolab/resource/kolab_2fa/
 */
$labels['created'] = 'Criado';
$labels['remove'] = 'Remover';
$labels['continue'] = 'Continuar';
$labels['yes'] = 'sim';
$labels['no'] = 'não';
$labels['label'] = 'Nome';
$labels['enterhighsecurity'] = 'Confirmar';
