<?php
/**
 * Localizations for the Kolab 2-Factor-Auth plugin
 *
 * Copyright (C) 2015, Kolab Systems AG
 *
 * For translation see https://www.transifex.com/projects/p/kolab/resource/kolab_2fa/
 */
$labels['secret'] = 'Секретный ключ';
$labels['created'] = 'Создана';
$labels['remove'] = 'Убрать';
$labels['continue'] = 'Продолжить';
$labels['settingstitle'] = 'Факторы авторизации';
$labels['or'] = 'или';
$labels['yes'] = 'да';
$labels['no'] = 'нет';
$labels['label'] = 'Имя';
$labels['qrcode'] = 'QR код';
$labels['showqrcode'] = 'Показать QR код';
$labels['verifycode'] = 'Подтвердить код';
$labels['factorsavesuccess'] = 'Успешно сохраненный фактор авторизации';
$labels['enterhighsecurity'] = 'Подтвердить';
